### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by ogencoglu** [wmcnally/kapao#1]
Can you clarify what kind of license there is for this?

**Comment by ignacio-ferreira-dev** [comment]
The license of this repository should be changed to GPL 3.0 as it uses yolov5 which has a GPL 3.0, right?
https://github.com/ultralytics/yolov5/blob/master/LICENSE

**Comment by wmcnally** [comment]
@ignacio-ferreira-dev yes, LICENSE file added.
