### ISSUE TITLE
the fusing operation described in paper

### ISSUE THREAD

**Issue by Laughing-q** [wmcnally/kapao#10]
Hi, this project is impressive, but I have some questions there.

"fusing the candidate keypoint objects with the candidate pose objects using a distance tolerance τfd." --from the paper.

maybe the fusing operation code is [there](https://github.com/wmcnally/kapao/blob/52d442aa649c95f75c487ead4bda6244c00e5c46/val.py#L103)?
but the code doesn't change variable `poses`. And I comment the code in `if data['use_kp_dets'] and nkp` then run youtube.py, the results are correct too.
is there a bug? or my mistake?

**Comment by wmcnally** [comment]
It changes the poses on [line 119](https://github.com/wmcnally/kapao/blob/52d442aa649c95f75c487ead4bda6244c00e5c46/val.py#L119). You won't notice a big difference. Fusion provides slightly more accurate predictions, mainly for the face keypoints.

**Comment by Laughing-q** [comment]
I didn't see `pose_kps = poses_mask[:, int(cls - 1)]`, thanks
