### ISSUE TITLE
How to run this on live webcam?

### ISSUE THREAD

**Issue by Guttappa1238** [wmcnally/kapao#11]
Hi,
i wanted to run this on my webcam, can anyone help me how to do that?

**Comment by wmcnally** [comment]
See [detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py#L92) from yolov5 to load the dataset from webcam. I would implement it myself, but I do not own a webcam so I cannot debug it.

**Comment by aafaqin** [comment]
> Hi, i wanted to run this on my webcam, can anyone help me how to do that?

You can try experimenting with the other function 
replace
`dataset = LoadImages(video_path, img_size=imgsz, stride=stride, auto=True)`
by this line
`dataset = LoadStreams(video_path, img_size=imgsz, stride=stride, auto=True)`
in demos/video.py and the exact specs of how to transform your arrays according to the new function you can find it in 
this file
https://github.com/ultralytics/yolov5/blob/master/utils/datasets.py
