### ISSUE TITLE
Loss for target grid which is both Pose and Keypoint object

### ISSUE THREAD

**Issue by nikhilchh** [wmcnally/kapao#12]
How do u compute loss for a target grid which represents both Keypoint and Pose object ?

**Comment by wmcnally** [comment]
A target grid cell represents a single object, so it cannot represent both object types. Please see section 3.2 in the paper. There are four loss components. All 4 are used to learn the pose objects, whereas only the first three (obj, box, cls) are used to learn the keypoint objects.

**Comment by nikhilchh** [comment]
There could be a situation when center of person and a keypoint lies in same grid. The Blue grid in Figure 4 is the perfect example. 
-Why did you make it Pose Object even though "right-hip" was also present in that grid ?
-If not that grid then which grid represents "right-hip" ?

**Comment by wmcnally** [comment]
Ah. That’s a toy example to help illustrate the targets. In practice, the grids are much bigger, and there are multiple - 160x160, 80x80, 40x40, 20x20. There are other measures of redundancy, including 3 anchor channels, and allowing neighbouring grid cells to also detect an object.

**Comment by nikhilchh** [comment]
I understood section 3.1 which is describing the output of the architecture. My doubt is regarding the Ground truth.
Does ground truth grid also have multiple anchor channels to store multiple objects in one grid. 
In the toy example the blue grid describes "human pose object", but i guess in reality that is just showing one of the anchor channel , another anchor channel will have small box to mark "right-hip" ? Correct me if I am wrong ?

**Comment by wmcnally** [comment]
You are correct regarding the anchor channels. Also, the target grid is the same shape as the prediction grid.

**Comment by nikhilchh** [comment]
Thanks for the clarifications. I hope this discussion will help others as well. :)
