### ISSUE TITLE
ERROR: Cannot uninstall 'certifi'.

### ISSUE THREAD

**Issue by Olin-YiYi** [wmcnally/kapao#16]
![error](https://user-images.githubusercontent.com/53260973/144154092-c1f2b6d7-165f-4d70-9ec7-3656edf79011.jpg)

**Comment by wmcnally** [comment]
Did you create a new conda environment as recommended in the setup instructions?

**Comment by Olin-YiYi** [comment]
Yes, I follow the setup step by step.

**Comment by Olin-YiYi** [comment]
It has been solved.
`pip install -r requirements.txt --ignore-installed`
