### ISSUE TITLE
Doubts regarding ANCHORS

### ISSUE THREAD

**Issue by nikhilchh** [wmcnally/kapao#17]
1- In the yolovXXX.yaml file there are anchor values in the multiple for 3. What are these values and how are they calculated ? 
2- Aren't they suppose to be 2 values for each anchor channel i.e. w and h ? Therefore 3x2 values. 3 channels and 2 value each ? 
3- In yaml file comments: Does P represent size of feature maps after certain layer ? Anchors are described as P3/8 , P4/16, P5/32 , P6/64. Can you elaborate that. This is also related to question 1. 
4- In the yolo.py file, you transform 4 values into x,y,w,h using anchor_grid, grid, stride. Can you explain that calculation of xy and wh ?
 
This image is related to yolo: Transformation of 4 values to box (xywh).
![image](https://user-images.githubusercontent.com/26286970/144275853-e01e2a14-bd53-41d7-95a3-3aff7797aa4a.png)

**Comment by wmcnally** [comment]
1. They are multiples of 2. The width and height are separted by a comma, please check again. The values are in pixels. They are hyperparameters inherited from yolov5. 
3. Yes. P3 size is equal to input size /8, P4 is input size /16, etc. 
4. The transformations are described in the paper (Sections 3.1 and 3.3). The transformations you cite are for an older version of yolo. KAPAO's are based on yolov5:
![image](https://user-images.githubusercontent.com/36055154/144278075-5f9436b1-c983-444e-b347-80800962b7e7.png)

**Comment by nikhilchh** [comment]
Got it. 
So  [19,27,  44,40,  38,94] are 3x2 anchor values for grid-P3 where P3 = input_size/8 .

Another question:
1- Aren't these anchor values very specific to image sizes of training data ? So are these particular values best when training image sizes are 1000+ ? 

My understanding is that for a data with 1000x1000 images and grid 8x8. One would find best anchor sizes to cover the reality and have best variation. Which is done using K-means. So does it mean:
1- If i want to train with 500x500 i need to find new optimal anchor values ? 
2- If i train with 1000x1000 then optimal input size for inference is also 1000x1000 even though I can inference on 500x500 as its a fully conv neural network ?

**Comment by wmcnally** [comment]
> Aren't these anchor values very specific to image sizes of training data ? 

To some extent, yes, they are specific to the input size. That being said, they are also flexible: the prediction for bbox width and height can be 0-4x the width and height of the anchor box, respectively. If you're looking to train on smaller images (e.g., 640x640), I recommend using the anchor boxes provided [here](https://github.com/ultralytics/yolov5/blob/master/models/yolov5s.yaml). 

> If i train with 1000x1000 then optimal input size for inference is also 1000x1000

Yes. That is generally true.

**Comment by nikhilchh** [comment]
Thanks a lot for all the clarifications. :)
