### ISSUE TITLE
Kapao structure

### ISSUE THREAD

**Issue by Ramt111** [wmcnally/kapao#20]
Is yolo5 the backbone of Kapao? the same weights? or you have trained the whole model?

**Comment by wmcnally** [comment]
Yes yolov5 is the backbone architecture. I initialized with the yolov5 weights and trained the whole model.

**Comment by Ramt111** [comment]
Thanks for your reply. Would you please let me know if you have used any augmentation at the training step? (like flip or different orientations) what about mosaic augmentation?

**Comment by wmcnally** [comment]
I use horizontal flip, scale, translation, mosaic, and hsv perturbations. See the [hyp.kp-p6.yaml](https://github.com/wmcnally/kapao/blob/master/data/hyps/hyp.kp-p6.yaml)
