### ISSUE TITLE
Inference showing error

### ISSUE THREAD

**Issue by Rottenblasters** [wmcnally/kapao#23]
I wanted to test the model on Google Colab. After setting up the requirements and models I ran the following command

![Kapao_error1](https://user-images.githubusercontent.com/68077049/145367859-ebf25631-89ec-48b3-9d11-c078c6cc9259.PNG)

The above error was shown. Any reason why?

For more clarity on what I have done you can view my colab notebook [link](https://colab.research.google.com/drive/1EPQk9Cz9QPXKqpd87sE8wOdgZIvKePf5?usp=sharing)

**Comment by wmcnally** [comment]
Sorry about that. Can you pull and try running again?

**Comment by Rottenblasters** [comment]
Yes it is working fine now!
