### ISSUE TITLE
Keypoint loss calculation

### ISSUE THREAD

**Issue by nikhilchh** [wmcnally/kapao#25]
In the code you apply l2 loss for keypoints.
And you consider the keypoints which have v>0.

So thus this mean that you didn't penalize the False Positive  keypoints. As you also filter the predictions based on `vis` tensor.

**Comment by wmcnally** [comment]
Sorry, what’s the question?

**Comment by nikhilchh** [comment]
Yes you got it right. 
What is the reason behind not penalizing FP kps ?

**Comment by wmcnally** [comment]
How would you penalize them without modification to the presented architecture? There are no keypoint-wise confidences in the predicted pose object representation.

**Comment by nikhilchh** [comment]
Ok got it. Thanks
