### ISSUE TITLE
Can this implementation be used for key-point object detection?

### ISSUE THREAD

**Issue by VikasRajashekar** [wmcnally/kapao#27]
First of all congrats on great work. 
I have a scenario where we try to detect/track objects by the central key point of the object without a bounding box.
Do you think the KAPAO can be sued for this purpose?

**Comment by wmcnally** [comment]
Yes it could if you had the training data. 

I’m guessing in your application simply using the center of the object bounding box is not accurate enough?

**Comment by CGong1020** [comment]
Are raw data training files 17 key points? What changes are needed to add 23 key points?

**Comment by wmcnally** [comment]
Steps for training on new dataset:
1. Create a new dataset configuration file similar to data/coco-kp.yaml and data/crowdpose.yaml
2. Modify utils/labels.py and val.py to suit your needs.
