### ISSUE TITLE
GPU or TensorRT

### ISSUE THREAD

**Issue by aafaqin** [wmcnally/kapao#3]
Can we run it on GPU?
The FPS is mentioned but hardware specs are not.
Can we convert it to tensorRT or OpenVino to run it on edge?

Amazing paper, found you on papers with code.

**Comment by wmcnally** [comment]
Thank you very much. It will run on GPU by default if cuda is available with torch. The reported FPS is for my machine which has a TITAN Xp GPU. I will update the readme to  mention the hardware in the inference demos section as well. I wish I had time to convert to tensorRT or OpenVino for edge applications, but unfortunately I do not.
