### ISSUE TITLE
precision & recall still 0 when i train coco2017

### ISSUE THREAD

**Issue by sayoko17** [wmcnally/kapao#30]
I train coco2017 with coco-kp.yaml weights yolov5s6.pt

in the result.csv ，mAP is 0.83，but  metrics precision &metrics recall still 0 。
run the val.py  I can see the score are most 0.003611，0.0027580，closed to 0。
eg.
{"image_id": 463730, "category_id": 1, "keypoints": [584.2581176757812, 211.4682159423828, 0.0, 584.8880615234375, 209.99844360351562, 0.0, 583.2449340820312, 210.3875274658203, 0.0, 585.7825927734375, 210.25306701660156, 0.0, 580.646484375, 211.4004364013672, 0.0, 587.0042724609375, 215.35562133789062, 0.0, 578.5013427734375, 216.1226348876953, 0.0, 589.2357177734375, 220.04568481445312, 0.0, 573.6966552734375, 222.9219970703125, 0.0, 585.150634765625, 220.6389617919922, 0.0, 577.4009399414062, 223.36631774902344, 0.0, 582.9385986328125, 228.6605987548828, 0.0, 577.1669921875, 228.58680725097656, 0.0, 579.8134155273438, 239.3750762939453, 0.0, 571.2628173828125, 239.9718475341797, 0.0, 575.2064208984375, 253.8463134765625, 0.0, 569.2610473632812, 254.59164428710938, 0.0], "score": 0.002862187335267663},

**Comment by wmcnally** [comment]
That is by design. KAPAO is only concerned with the COCO keypoint detection metrics (AP50 and AP), so val.py returns 0 for both precision and recall (to correctly interface with the training code).

**Comment by wangduyang** [comment]
[图片]
