### ISSUE TITLE
Batched inference (stacked images) 

### ISSUE THREAD

**Issue by Ramt111** [wmcnally/kapao#31]
By stacking several images (from a video or camera) in a tensor and then feeding it to the inference, do you expect a higher FPS? In other words, on my GPU, inference for one image takes 35% GPU usage, how to use the GPU full capacity at inference? Any idea?

**Comment by wmcnally** [comment]
Use the batch-size argument with val.py. On my setup I didn’t give any speed up in terms of ms / image.

**Comment by Ramt111** [comment]
1-I thought that batch-size argument defines the number of working GPUs at the inference, isn't it?
2-my question is if we can do anything to run the inference on a movie at the maximum power of only one GPU?

**Comment by wmcnally** [comment]
> 1-I thought that batch-size argument defines the number of working GPUs at the inference, isn't it?

No, the batch-size argument in val.py reflects the batch-size used during validation, which is performed on 1 GPU.

> 2-my question is if we can do anything to run the inference on a movie at the maximum power of only one GPU?

You would need to create a new dataloader for this. However, if increasing the batch-size in val.py does not give you a speed-up, then I don't expect any speed-up for the scenario you describe.
