### ISSUE TITLE
Error when i run train.py in crowdpose datasets

### ISSUE THREAD

**Issue by yiweike** [wmcnally/kapao#32]
When i run kapao-s in crowdpose, there are some errors
' (kapao) ywk@hello-Precision-3640-Tower:~/Desktop/Paper/kapao$ python -m torch.distributed.launch --nproc_per_node 4 train.py \
> --img 1280 \
> --batch 128 \
> --epochs 300 \
> --data data/crowdpose.yaml \
> --hyp data/hyps/hyp.kp-p6.yaml \
> --val-scales 1 \
> --val-flips -1 \
> --weights yolov5s6.pt \
> --project runs/cp_s_e300 \
> --name train \
> --workers 128 \
> --noval
/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
train: weights=yolov5s6.pt, cfg=, data=data/crowdpose.yaml, hyp=data/hyps/hyp.kp-p6.yaml, epochs=300, batch_size=128, imgsz=1280, rect=False, resume=False, nosave=False, noval=True, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=128, project=runs/cp_s_e300, entity=None, name=train, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=0, freeze=0, patience=100, val_scales=[1.0], val_flips=[-1], autobalance=False
Traceback (most recent call last):
  File "train.py", line 601, in <module>
    main(opt)
  File "train.py", line 489, in main
    assert torch.cuda.device_count() > LOCAL_RANK, 'insufficient CUDA devices for DDP command'
AssertionError: insufficient CUDA devices for DDP command
YOLOv5 🚀 2021-12-29 torch 1.9.1+cu102 CUDA:0 (GeForce RTX 2080 Ti, 11012.4375MB)

Added key: store_based_barrier_key:1 to store for rank: 0
Traceback (most recent call last):
  File "train.py", line 601, in <module>
    main(opt)
  File "train.py", line 489, in main
    assert torch.cuda.device_count() > LOCAL_RANK, 'insufficient CUDA devices for DDP command'
AssertionError: insufficient CUDA devices for DDP command
Traceback (most recent call last):
  File "train.py", line 601, in <module>
    main(opt)
  File "train.py", line 489, in main
    assert torch.cuda.device_count() > LOCAL_RANK, 'insufficient CUDA devices for DDP command'
AssertionError: insufficient CUDA devices for DDP command
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 17304) of binary: /home/ywk/anaconda3/envs/kapao/bin/python
Traceback (most recent call last):
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/run.py", line 692, in run
    )(*cmd_args)
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
            train.py FAILED            
=======================================
Root Cause:
[0]:
  time: 2022-01-05_18:05:39
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 17304)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2022-01-05_18:05:39
  rank: 2 (local_rank: 2)
  exitcode: 1 (pid: 17305)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[2]:
  time: 2022-01-05_18:05:39
  rank: 3 (local_rank: 3)
  exitcode: 1 (pid: 17306)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************
 '
can you tell me how to solve the problem?
Thx!

**Comment by wmcnally** [comment]
Did you read your error message? It says insufficient CUDA devices for DDP command. You only have 1 gpu, so don’t use the distributed module and lower the batch size. Also set the number of workers equal to the number cpu cores.

**Comment by yiweike** [comment]
> Did you read your error message? It says insufficient CUDA devices for DDP command. You only have 1 gpu, so don’t use the distributed module and lower the batch size. Also set the number of workers equal to the number cpu cores.

Thanks for your reply.
I solved the problem above. And a new error arised 
' (kapao) ywk@hello-Precision-3640-Tower:~/Desktop/Paper/kapao$ python -m torch.distributed.launch --nproc_per_node 1 train.py \
> --img 1280 \
> --batch 4 \
> --epochs 10 \
> --data data/crowdpose.yaml \
> --hyp data/hyps/hyp.kp-p6.yaml \
> --val-scales 1 \
> --val-flips -1 \
> --weights yolov5s6.pt \
> --project runs/cp_s_e300 \
> --name train \
> --workers 4 \
> --noval
/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
train: weights=yolov5s6.pt, cfg=, data=data/crowdpose.yaml, hyp=data/hyps/hyp.kp-p6.yaml, epochs=10, batch_size=4, imgsz=1280, rect=False, resume=False, nosave=False, noval=True, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=4, project=runs/cp_s_e300, entity=None, name=train, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=0, freeze=0, patience=100, val_scales=[1.0], val_flips=[-1], autobalance=False
YOLOv5 🚀 2021-12-29 torch 1.9.1+cu102 CUDA:0 (GeForce RTX 2080 Ti, 11012.4375MB)

Added key: store_based_barrier_key:1 to store for rank: 0
Rank 0: Completed store-based barrier for 1 nodes.
hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.3, cls_pw=1.0, obj=0.7, obj_pw=1.0, kp=0.025, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.9, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, kp_bbox=0.05
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs/cp_s_e300', view at http://localhost:6006/
Overriding model.yaml nc=80 with nc=43

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  3    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1    885504  models.common.Conv                      [256, 384, 3, 2]              
  8                -1  1    665856  models.common.C3                        [384, 384, 1]                 
  9                -1  1   1770496  models.common.Conv                      [384, 512, 3, 2]              
 10                -1  1    656896  models.common.SPP                       [512, 512, [3, 5, 7]]         
 11                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 12                -1  1    197376  models.common.Conv                      [512, 384, 1, 1]              
 13                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 14           [-1, 8]  1         0  models.common.Concat                    [1]                           
 15                -1  1    813312  models.common.C3                        [768, 384, 1, False]          
 16                -1  1     98816  models.common.Conv                      [384, 256, 1, 1]              
 17                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 18           [-1, 6]  1         0  models.common.Concat                    [1]                           
 19                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 20                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 21                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 22           [-1, 4]  1         0  models.common.Concat                    [1]                           
 23                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 24                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 25          [-1, 20]  1         0  models.common.Concat                    [1]                           
 26                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 27                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 28          [-1, 16]  1         0  models.common.Concat                    [1]                           
 29                -1  1    715008  models.common.C3                        [512, 384, 1, False]          
 30                -1  1   1327872  models.common.Conv                      [384, 384, 3, 2]              
 31          [-1, 12]  1         0  models.common.Concat                    [1]                           
 32                -1  1   1313792  models.common.C3                        [768, 512, 1, False]          
 33  [23, 26, 29, 32]  1    184896  models.yolo.Detect                      [43, [[19, 27, 44, 40, 38, 94], [96, 68, 86, 152, 180, 137], [140, 301, 303, 264, 238, 542], [436, 615, 739, 380, 925, 792]], [128, 256, 384, 512]]
Model Summary: 368 layers, 12525312 parameters, 12525312 gradients, 17.1 GFLOPs

Transferred 464/472 items from yolov5s6.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 77 weight, 81 weight (no decay), 81 bias
train: Scanning 'data/datasets/crowdpose/kp_labels/img_txt/trainval.cache' images and labels... 12000 found, 0 missing, 0 empty, 0 corrupted: 100%|█| 12000/12000 [00:00
val: Scanning 'data/datasets/crowdpose/kp_labels/img_txt/test.cache' images and labels... 8000 found, 0 missing, 0 empty, 0 corrupted: 100%|█| 8000/8000 [00:00<?, ?it/s

autoanchor: Analyzing anchors... anchors/target = 6.00, Best Possible Recall (BPR) = 1.0000
Image sizes 1280 train, 1280 val
Using 4 dataloader workers
Logging results to runs/cp_s_e300/train4
Starting training for 10 epochs...

     Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
       0/9     2.94G    0.1112    0.2681   0.04417    0.5449       350      1280:   0%|                                              | 1/3000 [00:07<6:24:24,  7.69s/it]Reducer buckets have been rebuilt in this iteration.
       0/9     3.25G   0.05154    0.3148   0.02836    0.1994       300      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:30<00:00,  6.66it/s]

     Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
       1/9     3.25G    0.0409    0.3121   0.02147    0.1559       294      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:06<00:00,  7.03it/s]

     Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
       2/9     3.25G   0.04209    0.3305   0.02012    0.1633       213      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:04<00:00,  7.06it/s]

     Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
       3/9     3.25G   0.03943    0.3091   0.01845    0.1462       537      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:04<00:00,  7.07it/s]

     Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
       4/9     3.25G   0.03803    0.3019   0.01726    0.1375       256      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:03<00:00,  7.08it/s]

     Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
       5/9     3.25G   0.03699    0.2972   0.01624    0.1298       300      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:06<00:00,  7.04it/s]

     Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
       6/9     3.25G   0.03602    0.2916   0.01564    0.1264       556      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:04<00:00,  7.06it/s]

     Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
       7/9     3.25G   0.03531    0.2875    0.0151    0.1224       434      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:03<00:00,  7.08it/s]

     Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
       8/9     3.25G    0.0345     0.286   0.01455    0.1172       361      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:04<00:00,  7.06it/s]

     Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
       9/9     3.25G    0.0339    0.2787   0.01413    0.1132       490      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:03<00:00,  7.08it/s]
Processing val images: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [01:59<00:00, 16.69it/s]
loading annotations into memory...
Done (t=0.74s)
creating index...
index created!
Loading and preparing results...
DONE (t=10.57s)
creating index...
index created!
Traceback (most recent call last):
  File "train.py", line 601, in <module>
    main(opt)
  File "train.py", line 499, in main
    train(opt.hyp, opt, device)
  File "train.py", line 360, in train
    flips=val_flips)
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/ywk/Desktop/Paper/kapao/val.py", line 284, in run
    eval = COCOeval(coco, result, iouType='keypoints')
  File "/home/ywk/.local/lib/python3.6/site-packages/crowdposetools/cocoeval.py", line 88, in __init__
    self.params = Params(iouType=iouType)  # parameters
  File "/home/ywk/.local/lib/python3.6/site-packages/crowdposetools/cocoeval.py", line 634, in __init__
    self.setKpParams()
  File "/home/ywk/.local/lib/python3.6/site-packages/crowdposetools/cocoeval.py", line 621, in setKpParams
    (0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/numpy/core/function_base.py", line 113, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4431) of binary: /home/ywk/anaconda3/envs/kapao/bin/python
Traceback (most recent call last):
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/run.py", line 692, in run
    )(*cmd_args)
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
            train.py FAILED            
=======================================
Root Cause:
[0]:
  time: 2022-01-06_16:08:20
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 4431)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************
'
Could you tell me how to solve ' ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4431) of binary: '?
Thx

**Comment by wmcnally** [comment]
First, because you only have 1 GPU you don't need to use the distributed module, i.e. you can train simply with 
`python train.py --img-size 1280 ...`. 

Second, the error relates to the CrowdPose evaluation code:
> File "/home/ywk/.local/lib/python3.6/site-packages/crowdposetools/cocoeval.py", line 621, in setKpParams
> (0.95 - .5) / .05) + 1, endpoint=True)
> File "<array_function internals>", line 6, in linspace
> File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/numpy/core/function_base.py", line 113, in linspace
> num = operator.index(num)
> TypeError: 'numpy.float64' object cannot be interpreted as an integer

[The bug was fixed a couple of months ago](https://github.com/Jeff-sjtu/CrowdPose/blob/master/crowdpose-api/PythonAPI/crowdposetools/cocoeval.py#L620-L623), so please re-install the CrowdPose python api following the instructions in the readme. In the future, please try to diagnose and fix the problem on your own before creating an issue. Thanks!

**Comment by iremonur** [comment]
> > Did you read your error message? It says insufficient CUDA devices for DDP command. You only have 1 gpu, so don’t use the distributed module and lower the batch size. Also set the number of workers equal to the number cpu cores.
> 
> Thanks for your reply. I solved the problem above. And a new error arised ' (kapao) ywk@hello-Precision-3640-Tower:~/Desktop/Paper/kapao$ python -m torch.distributed.launch --nproc_per_node 1 train.py \
> 
> > --img 1280 
> > --batch 4 
> > --epochs 10 
> > --data data/crowdpose.yaml 
> > --hyp data/hyps/hyp.kp-p6.yaml 
> > --val-scales 1 
> > --val-flips -1 
> > --weights yolov5s6.pt 
> > --project runs/cp_s_e300 
> > --name train 
> > --workers 4 
> > --noval
> > /home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
> > and will be removed in future. Use torch.distributed.run.
> > Note that --use_env is set by default in torch.distributed.run.
> > If your script expects `--local_rank` argument to be set, please
> > change it to read from `os.environ['LOCAL_RANK']` instead. See
> > https://pytorch.org/docs/stable/distributed.html#launch-utility for
> > further instructions
> 
> FutureWarning, train: weights=yolov5s6.pt, cfg=, data=data/crowdpose.yaml, hyp=data/hyps/hyp.kp-p6.yaml, epochs=10, batch_size=4, imgsz=1280, rect=False, resume=False, nosave=False, noval=True, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=4, project=runs/cp_s_e300, entity=None, name=train, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=0, freeze=0, patience=100, val_scales=[1.0], val_flips=[-1], autobalance=False YOLOv5 rocket 2021-12-29 torch 1.9.1+cu102 CUDA:0 (GeForce RTX 2080 Ti, 11012.4375MB)
> 
> Added key: store_based_barrier_key:1 to store for rank: 0 Rank 0: Completed store-based barrier for 1 nodes. hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.3, cls_pw=1.0, obj=0.7, obj_pw=1.0, kp=0.025, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.9, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, kp_bbox=0.05 Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5 rocket runs (RECOMMENDED) TensorBoard: Start with 'tensorboard --logdir runs/cp_s_e300', view at http://localhost:6006/ Overriding model.yaml nc=80 with nc=43
> 
> ```
>              from  n    params  module                                  arguments                     
> ```
> 
> 0 -1 1 3520 models.common.Focus [3, 32, 3] 1 -1 1 18560 models.common.Conv [32, 64, 3, 2] 2 -1 1 18816 models.common.C3 [64, 64, 1] 3 -1 1 73984 models.common.Conv [64, 128, 3, 2] 4 -1 3 156928 models.common.C3 [128, 128, 3] 5 -1 1 295424 models.common.Conv [128, 256, 3, 2] 6 -1 3 625152 models.common.C3 [256, 256, 3] 7 -1 1 885504 models.common.Conv [256, 384, 3, 2] 8 -1 1 665856 models.common.C3 [384, 384, 1] 9 -1 1 1770496 models.common.Conv [384, 512, 3, 2] 10 -1 1 656896 models.common.SPP [512, 512, [3, 5, 7]] 11 -1 1 1182720 models.common.C3 [512, 512, 1, False] 12 -1 1 197376 models.common.Conv [512, 384, 1, 1] 13 -1 1 0 torch.nn.modules.upsampling.Upsample [None, 2, 'nearest'] 14 [-1, 8] 1 0 models.common.Concat [1] 15 -1 1 813312 models.common.C3 [768, 384, 1, False] 16 -1 1 98816 models.common.Conv [384, 256, 1, 1] 17 -1 1 0 torch.nn.modules.upsampling.Upsample [None, 2, 'nearest'] 18 [-1, 6] 1 0 models.common.Concat [1] 19 -1 1 361984 models.common.C3 [512, 256, 1, False] 20 -1 1 33024 models.common.Conv [256, 128, 1, 1] 21 -1 1 0 torch.nn.modules.upsampling.Upsample [None, 2, 'nearest'] 22 [-1, 4] 1 0 models.common.Concat [1] 23 -1 1 90880 models.common.C3 [256, 128, 1, False] 24 -1 1 147712 models.common.Conv [128, 128, 3, 2] 25 [-1, 20] 1 0 models.common.Concat [1] 26 -1 1 296448 models.common.C3 [256, 256, 1, False] 27 -1 1 590336 models.common.Conv [256, 256, 3, 2] 28 [-1, 16] 1 0 models.common.Concat [1] 29 -1 1 715008 models.common.C3 [512, 384, 1, False] 30 -1 1 1327872 models.common.Conv [384, 384, 3, 2] 31 [-1, 12] 1 0 models.common.Concat [1] 32 -1 1 1313792 models.common.C3 [768, 512, 1, False] 33 [23, 26, 29, 32] 1 184896 models.yolo.Detect [43, [[19, 27, 44, 40, 38, 94], [96, 68, 86, 152, 180, 137], [140, 301, 303, 264, 238, 542], [436, 615, 739, 380, 925, 792]], [128, 256, 384, 512]] Model Summary: 368 layers, 12525312 parameters, 12525312 gradients, 17.1 GFLOPs
> 
> Transferred 464/472 items from yolov5s6.pt Scaled weight_decay = 0.0005 optimizer: SGD with parameter groups 77 weight, 81 weight (no decay), 81 bias train: Scanning 'data/datasets/crowdpose/kp_labels/img_txt/trainval.cache' images and labels... 12000 found, 0 missing, 0 empty, 0 corrupted: 100%|█| 12000/12000 [00:00 val: Scanning 'data/datasets/crowdpose/kp_labels/img_txt/test.cache' images and labels... 8000 found, 0 missing, 0 empty, 0 corrupted: 100%|█| 8000/8000 [00:00<?, ?it/s
> 
> autoanchor: Analyzing anchors... anchors/target = 6.00, Best Possible Recall (BPR) = 1.0000 Image sizes 1280 train, 1280 val Using 4 dataloader workers Logging results to runs/cp_s_e300/train4 Starting training for 10 epochs...
> 
> ```
>  Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
>    0/9     2.94G    0.1112    0.2681   0.04417    0.5449       350      1280:   0%|                                              | 1/3000 [00:07<6:24:24,  7.69s/it]Reducer buckets have been rebuilt in this iteration.
>    0/9     3.25G   0.05154    0.3148   0.02836    0.1994       300      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:30<00:00,  6.66it/s]
> 
>  Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
>    1/9     3.25G    0.0409    0.3121   0.02147    0.1559       294      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:06<00:00,  7.03it/s]
> 
>  Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
>    2/9     3.25G   0.04209    0.3305   0.02012    0.1633       213      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:04<00:00,  7.06it/s]
> 
>  Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
>    3/9     3.25G   0.03943    0.3091   0.01845    0.1462       537      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:04<00:00,  7.07it/s]
> 
>  Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
>    4/9     3.25G   0.03803    0.3019   0.01726    0.1375       256      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:03<00:00,  7.08it/s]
> 
>  Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
>    5/9     3.25G   0.03699    0.2972   0.01624    0.1298       300      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:06<00:00,  7.04it/s]
> 
>  Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
>    6/9     3.25G   0.03602    0.2916   0.01564    0.1264       556      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:04<00:00,  7.06it/s]
> 
>  Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
>    7/9     3.25G   0.03531    0.2875    0.0151    0.1224       434      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:03<00:00,  7.08it/s]
> 
>  Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
>    8/9     3.25G    0.0345     0.286   0.01455    0.1172       361      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:04<00:00,  7.06it/s]
> 
>  Epoch   gpu_mem       box       obj       cls       kps    labels  img_size
>    9/9     3.25G    0.0339    0.2787   0.01413    0.1132       490      1280: 100%|█████████████████████████████████████████████| 3000/3000 [07:03<00:00,  7.08it/s]
> ```
> 
> Processing val images: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [01:59<00:00, 16.69it/s] loading annotations into memory... Done (t=0.74s) creating index... index created! Loading and preparing results... DONE (t=10.57s) creating index... index created! Traceback (most recent call last): File "train.py", line 601, in main(opt) File "train.py", line 499, in main train(opt.hyp, opt, device) File "train.py", line 360, in train flips=val_flips) File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context return func(*args, **kwargs) File "/home/ywk/Desktop/Paper/kapao/val.py", line 284, in run eval = COCOeval(coco, result, iouType='keypoints') File "/home/ywk/.local/lib/python3.6/site-packages/crowdposetools/cocoeval.py", line 88, in **init** self.params = Params(iouType=iouType) # parameters File "/home/ywk/.local/lib/python3.6/site-packages/crowdposetools/cocoeval.py", line 634, in **init** self.setKpParams() File "/home/ywk/.local/lib/python3.6/site-packages/crowdposetools/cocoeval.py", line 621, in setKpParams (0.95 - .5) / .05) + 1, endpoint=True) File "<**array_function** internals>", line 6, in linspace File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/numpy/core/function_base.py", line 113, in linspace num = operator.index(num) TypeError: 'numpy.float64' object cannot be interpreted as an integer ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4431) of binary: /home/ywk/anaconda3/envs/kapao/bin/python Traceback (most recent call last): File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py", line 193, in main() File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py", line 189, in main launch(args) File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launch.py", line 174, in launch run(args) File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/run.py", line 692, in run )(*cmd_args) File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 116, in **call** return launch_agent(self._config, self._entrypoint, list(args)) File "/home/ywk/anaconda3/envs/kapao/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent failures=result.failures, torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> 
> ```
>         train.py FAILED            
> ```
> 
> # =======================================
> Root Cause:
> [0]:
> time: 2022-01-06_16:08:20
> rank: 0 (local_rank: 0)
> exitcode: 1 (pid: 4431)
> error_file: <N/A>
> msg: "Process failed with exitcode 1"
> Other Failures: <NO_OTHER_FAILURES>
> 
> ' Could you tell me how to solve ' ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4431) of binary: '? Thx

Hi, I had the same error on Google COLAB, and I think it is caused by having only one GPU on COLAB. How did you solve this problem?
