### ISSUE TITLE
Question about tau_{ck}

### ISSUE THREAD

**Issue by Ramt111** [wmcnally/kapao#33]
How can I change the value of tau_{ck} in the code? I want to make it zero to have a higher number of keypoint confidences returned as described in Section 3.4 of the paper.

**Comment by wmcnally** [comment]
Use the conf-thres-kp argument. Please see the command in the readme for the red light green light demo, which only plots keypoint objects.

**Comment by Ramt111** [comment]
Thanks. Did you notice any negative impact on AP if tau_{ck} is taken to be small?

**Comment by wmcnally** [comment]
The AP might decrease but not a lot. I wouldn't expect the AP to drop by more than 0.5 points. You can test it out using val.py. Setting `--conf-thres-kp` close to zero increases latency, so be wary of that. The settings I used in the red light green light demo seemed to work well.

**Comment by Ramt111** [comment]
Thank you for your always helpful responses. I would ask you one more question.  Assume that we'd like to have different --conf-thres-kp for different keypoints. You might think of a scenario in which for example the wrist and elbow keypoints confidences are more important to us so we want to have the values of confidence for those particular keypoints by choosing a small --conf-thres-kp for them but not for the rest of keypoints to avoid large latency. Do I need to change ru_nms(data,model) in your val.py?

**Comment by wmcnally** [comment]
Yes. This should be a straight forward modification. In `run_nms()`, pay attention to how the `classes` argument is used with `non_maximum_suppression_kp()`. Hope this helps!
