### ISSUE TITLE
Multi-Class Pose estimation 

### ISSUE THREAD

**Issue by abhigoku10** [wmcnally/kapao#34]
@wmcnally  thanks for the code base , how to extend the current code base to train for both person pose estimation and animal pose estimation ? what are all the changes to be made for multi class pose estimation

**Comment by wmcnally** [comment]
You should add more classes to the dataset config file. You should have a person class and an animal class (or however many species you wish to detect). 

Steps for training on new dataset:
1. Create a new dataset configuration file similar to data/coco-kp.yaml and data/crowdpose.yaml
2. Modify utils/labels.py and val.py to suit your needs.
