### ISSUE TITLE
Input image size and speed

### ISSUE THREAD

**Issue by Ramt111** [wmcnally/kapao#35]
In your paper, it's mentioned that the input image is resized to 1280*1280. My question is if there is a version of Kapao which takes a smaller image size (e.g. 640) which can speed up the inference at the expense of lower accuracy?

**Comment by wmcnally** [comment]
Yes, you can use smaller input sizes during inference with the versions provided. See the figure below, which plots the accuracy-latency trade-off for input sizes ranging from 640 to 1280. For KAPAO-M and L, lowering the input size to 1024 reduces latency by 30% and has a negligible effect on the accuracy.
![image](https://user-images.githubusercontent.com/36055154/150431444-e10aa7b2-6eff-4fd7-9601-f7130dc05bd5.png)
