### ISSUE TITLE
Convert to onnx

### ISSUE THREAD

**Issue by lofyol** [wmcnally/kapao#44]
After converting the PT model to onnx, the simplifier will report an error, and the onnxruntime will also report an error (failed: node (mul_3056) op (mul) [shapeinferenceerror] incompatible dimensions). Is this the reason for yolov5？

**Comment by lofyol** [comment]
Can you solve it

**Comment by lofyol** [comment]
y[..., -self.num_coords:] = y[..., -self.num_coords:] * 4. - 2.
 y[..., -self.num_coords:] *= self.anchor_grid[i].repeat((1, 1, 1, 1, self.num_coords // 2))
 y[..., -self.num_coords:] += (self.grid[i] * self.stride[i]).repeat((1, 1, 1, 1, self.num_coords // 2))

**Comment by favorxin** [comment]
> After converting the PT model to onnx, the simplifier will report an error, and the onnxruntime will also report an error (failed: node (mul_3056) op (mul) [shapeinferenceerror] incompatible dimensions). Is this the reason for yolov5？

Hello！Do you solve the problem while converting the model to onnx?

**Comment by lofyol** [comment]
> > After converting the PT model to onnx, the simplifier will report an error, and the onnxruntime will also report an error (failed: node (mul_3056) op (mul) [shapeinferenceerror] incompatible dimensions). Is this the reason for yolov5？
> 
> Hello！Do you solve the problem while converting the model to onnx?

yes

**Comment by Sanidhya27** [comment]
How did u resolve the issue?
