### ISSUE TITLE
DEKR performance on COCO val2017 are much higher than what is reported in your paper

### ISSUE THREAD

**Issue by wuzhenyusjtu** [wmcnally/kapao#47]
Here is a table summarizing the performance of DEKR and KAPAO on COCO val 2017. The numbers are directly copied from DEKR's Table 2 and KAPAO's Table 1. We can the that the number reported in DEKR's paper is much higher that what is reported in KAPAO's paper. Is there anything I misunderstood? Thank you and hope your reply.
| Method   | TTA | Input Size | Parameters | AP   | AR   |
|----------|-----|------------|------------|------|------|
| DEKR-W48 | N   | 640        | 65.7       | **66.3** | **73.2** |
| DEKR-W48 | N   | 640        | N/A        | **71**   | **76**   |
| KAPAO-S  | N   | 1280       | 12.6       | 63   | 70.2 |

**Comment by wmcnally** [comment]
DEKR Table 2 includes horizontal flipping, KAPAO Table 1 does not. DEKR Table 2 uses a model-agnostic pose scoring network which adds ~0.5 AP. For fairness, I did not include that either (since it is model agnostic it could be added to KAPAO too).
