### ISSUE TITLE
Typos in Eq (3) and Eq (4)?

### ISSUE THREAD

**Issue by wuzhenyusjtu** [wmcnally/kapao#48]
Dear McNally:

This is such a fantastic work! We love it.

I have a few questions below regarding Eq. 4:

1. In Eq. 3 and Eq. 4, should the _A_w/s_ be _A_h/s_ for _t_h_ and _v_{yk}_?
2. Eq.4 is an extension of _v's_ parameterization from YOLOv4/5.
2.1. Do you have any ablation study on the parameterization's extension? Why don't you adopt 4σ(v)−2 for _v_? 
2.2. What are the intuitions behind?

Thanks!

**Comment by wmcnally** [comment]
`In Eq. 3 and Eq. 4, should the A_w/s be A_h/s for t_h and v{yk}_?`

Yes! Nice catch. We also caught this typo but haven't updated the arxiv paper yet. New version coming soon!

`Do you have any ablation study on the parameterization's extension? Why don't you adopt 4σ(v)−2 for v? What are the intuitions behind?` 

Is there a typo in your question? We _do_ adopt 4σ(v)−2 for v. The intution is to constrain the keypoints to [-2, 2] times the anchor box dimensions (normalized by grid scale). Given that the object bounding box t dimensions were already constrained to [0, 4] times the anchor box, we thought the keypoint range of [-2, 2] was intuitive.
