### ISSUE TITLE
TensorFlow and TFlite export

### ISSUE THREAD

**Issue by lrob** [wmcnally/kapao#5]
I've seen that in the past some commits mention the possibility to export the model in TensorFlow and in TFLite. Is this operation still possible? And if it is the case, how can it be done?

**Comment by wmcnally** [comment]
TF / TFLite export was available in the original yolov5 code, but I removed it as I wasn't sure that my modifications to the model would be compatible. If you're interested in converting, a good place to start looking would be [export.py](https://github.com/ultralytics/yolov5/blob/master/export.py) in ultralytics/yolov5.
