### ISSUE TITLE
 'Upsample' object has no attribute 'recompute_scale_factor'

### ISSUE THREAD

**Issue by nikhilchh** [wmcnally/kapao#55]
I got an error when i used latest pytorch 1.11.0. 
The error : "Upsample' object has no attribute 'recompute_scale_factor"

Yolo repo managers also modified their code to fix the same.
https://github.com/ultralytics/yolov5/pull/6932

Does it also make sense for Kapao repo ?

**Comment by wmcnally** [comment]
Yes errors might occur using newer versions of torch. That's why the requirements file has torch==1.9.1
