### ISSUE TITLE
Kapao output is flip of Coco data

### ISSUE THREAD

**Issue by nikhilchh** [wmcnally/kapao#56]
IS kapao out a flipped version of COCO data ? 

Keypoints which are right in coco seems left in kapao output.  Is this is the case ? If yes why ?

**Comment by wmcnally** [comment]
That should not be the case. Can you provide an example where the keypoints are flipped?

**Comment by nikhilchh** [comment]
in the demos/image.py file:

model(img, augment=True, kp_flip=data['kp_flip'], scales=data['scales'], flips=data['flips'])[0]

I think might be causing it. Isn't augment supposed to be False for inferencing ?

**Comment by nikhilchh** [comment]
Or maybe my understanding of left and right is wrong.

Does left mean from left from the perspective of the viewer of the image. or Left from perspective of the person being labelled ?

**Comment by wmcnally** [comment]
It is from the perspective of the person being labelled.

**Comment by nikhilchh** [comment]
thanks :)
