### ISSUE TITLE
kp-bbox rescale problem

### ISSUE THREAD

**Issue by dongxiaolong** [wmcnally/kapao#60]
I install the requirement successfully, I have already run the code, It seems perfectly. But when I run the command`python demos/image.py --bbox --kp-bbox`, I find the kp-bbox draw wrong, I think the mistake that occured ,becuase wrong rescaling. Maybe when you run the command, you will get the problem. Could you fix it ? Thanks for you work.

**Comment by dongxiaolong** [comment]
![crowdpose_100024_kapao_l_coco_kpbbox_kp_obj](https://user-images.githubusercontent.com/23193031/168944078-ff2b81e1-b9b4-424a-9473-869bae4f81c6.png)

**Comment by dongxiaolong** [comment]
![crowdpose_100024_kapao_l_coco_bbox_pose_kpbbox_kp_obj](https://user-images.githubusercontent.com/23193031/168944186-a25c6405-db1e-42b0-8710-81494cc2f99c.png)

**Comment by V63A** [comment]
I think it rescales the kp-bbox 2 times.
At line 88 in demos/image.py, function post_process_batch(...) was called. In this function, the mutable object kp_dets do the rescale calculation and some values are replaced(line 108 in vals.py). Later on, line 105 in demos/images.py do the rescale again.

Therefore,  you could import module copy and call function post_process_batch as 'post_process_batch ( ... , copy.deepcopy(kp_dets ))'.

**Comment by dongxiaolong** [comment]
> I think it rescales kp-bboxs 2 times. At line 88 in demos/image.py, function post_process_batch(...) was called. In this function, the mutable object kp_dets do the rescale calculation and some values are replaced(line 108 in vals.py). Later on, line 105 in demos/images.py do the rescale again.
> 
> Therefore, you could import module copy and call function post_process_batch as 'post_process_batch ( ... , copy.deepcopy(kp_dets ))'.

Issue was settled ! Thanks for your helping.
