### ISSUE TITLE
Albumentations leads to batch concatenating fail

### ISSUE THREAD

**Issue by V63A** [wmcnally/kapao#64]
Hi, thank you for the great work!

I noticed that you comment out the package 'albumentations' in requirement.txt, but I guess you just follow the setting of yolov5. Have you ever trained with this package? I tried to train with it, and got this error:

![image](https://user-images.githubusercontent.com/49903803/172809035-780aeb79-3af3-41ca-9db6-476e7770dc82.png)

It failed to concatenate labels due to the mismatched dimension, and I found out that the shape of variable 'labels' of an image without any label information will be changed after albumentations calcuation([line 594 in utils/datasets.py](https://github.com/wmcnally/kapao/blob/ad507c2a00de330eb40d58cf0f4614d82d3c86b5/utils/datasets.py#L594) ), from (0,56) to (0,).

So, if there is any recommended modified, or manually coverts the shape back with value 0 is ok?

**Comment by wmcnally** [comment]
No I have not tried training with this package. You may have to modify the Albumentations class in utils.augmentations to get it working.
