### ISSUE TITLE
AssertionError: Labels already generated. Remove or choose new name for labels

### ISSUE THREAD

**Issue by dcsrgh** [wmcnally/kapao#65]
I press the 'Ctrl+Z', when the code is running. But when I run the code again, there is the error.
'AssertionError: Labels already generated. Remove or choose new name for labels'

I look for the process number by 'lsof -i:6006'. But there is nothing.
How do I close the tensorboard process.
Help me, please.
Thank you.

**Comment by zstuli** [comment]
cd data/datasets/coco ,then rm -rf kp_labels 
because the original foloder has the same name folder,which prevents the system from creating new folders

**Comment by wmcnally** [comment]
Thanks @zstuli!
