### ISSUE TITLE
puzzle about Algorithm 1

### ISSUE THREAD

**Issue by x2ss** [wmcnally/kapao#7]
Hi，

I am deeply impressed by your work, however I feel puzzled about the Algorithm 1 in the paper. 

There are some symbols in Algorithm 1 are not defined in the description, also the function of Pˆ ∗m[k, 3] < max(Oˆkc ) is not well explained. 

I would be deeply appreciated if some modifications can be made to Algorithm 1 to make it clear. 

Thanks!

**Comment by wmcnally** [comment]
Algorithm 1 summarizes [L97-L119 in val.py](https://github.com/wmcnally/kapao/blob/master/val.py#L97-L119). If you review that code it might help you understand better. 

P* are the poses whose confidence is greater than tau_fc. 'm' is the index of the pose in P* whose keypoint 'k' is nearest the keypoint object O^k. The if statement you're referring to with P*m[k, 3] < max(Oˆkc ) means "if the distance of the keypoint object is less than tau_fd **and** the confidence of the pose object keypoint is less than the confidence of the keypoint object, then overwrite the pose object keypoint with the keypoint object. 

Actually, the keypoint object confidence should be written as O^k_{p_o} * max(O^k_c). Thank you for bringing that to my attention.

**Comment by x2ss** [comment]
> Algorithm 1 roughly summarizes [L97-L119 in val.py](https://github.com/wmcnally/kapao/blob/master/val.py#L97-L119). If you review that code it might help you understand better.
> 
> P* are the poses whose confidence is greater than tau_fc. 'm' is the index of the pose in P* whose keypoint 'k' is nearest the keypoint object O^k. The if statement you're referring to with "d < tau_fd and P*m[k, 3] < max(Oˆkc )" means "if the distance of the keypoint object is less than tau_fd **and** the confidence of the pose object keypoint (initialized with zero confidence) is less than the confidence of the keypoint object, then overwrite the pose object keypoint with the keypoint object."
> 
> Actually, the keypoint object confidence should be written as O^k_{p_o} * max(O^k_c). Thank you for bringing that to my attention.

Thanks for your kind reply. 

Does "overwrite" means that making that point as a keypoint object instead of a pose object keypoint? As stated as Pˆ ∗m[k] = (Oˆkbx, Oˆkby, max(Oˆkc )) which is below "d < tau_fd and P*m[k, 3] < max(Oˆkc )"?

**Comment by wmcnally** [comment]
Yes, it means for the predicted pose P*m, set the keypoint 'k' equal to the keypoint object center.

**Comment by x2ss** [comment]
Thanks for your kind answer！
