### ISSUE TITLE
Accuracy-speed trade-off for input sizes ranging from 640 to 1280

### ISSUE THREAD

**Issue by nikhilchh** [wmcnally/kapao#96]
![image](https://github.com/wmcnally/kapao/assets/26286970/0951725f-f02b-432f-a196-9b2e6e6d9d08)

In this analysis have you trained the model for different input sizes or the model is only trained with a specific input size and only at inference time you tried different input sizes to see their impact on accuracy and speed ?

**Comment by wmcnally** [comment]
The latter

**Comment by nikhilchh** [comment]
Thank you for your response
