### ISSUE TITLE
Number of Grids: 3 vs 4

### ISSUE THREAD

**Issue by nikhilchh** [wmcnally/kapao#97]
1- I observed that yolo have used 3 grids for "Detect" and therefore 3 set of anchors have been defined. This is common in v5 till v8. 
What was the reason for using 4 set of grids and anchors in Kapao? I also checked the commit of yolov5 which you have used that also had 3 set of grids and anchors. 

2- For 640x640 image resolution does it make sense to use 3 grids ? The aim is create a further smaller version of the model. 
3- Any plans of creating KAPAO (code base) based on yolov8 ?

**Comment by wmcnally** [comment]
The "P6" version of yolov5 (used for 1280 input image size) uses 4 grids with 3 anchors each. 
https://github.com/ultralytics/yolov5/blob/35fe03146187cd8b1c09dd3e72ae678bb9ec5b86/models/hub/yolov5l6.yaml
